name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  TrainModel: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ReviewPredictor.Trainer/ReviewPredictor.Trainer.csproj
    - name: Build
      run: dotnet build ReviewPredictor.Trainer/ReviewPredictor.Trainer.csproj --configuration Release --no-restore
    - name: Train model
      working-directory: ReviewPredictor.Trainer
      run: dotnet run --project ReviewPredictor.Trainer.csproj
    - name: Upload model.zip
      uses: actions/upload-artifact@v2
      with:
        name: model.zip
        path: ReviewPredictor.Trainer/model.zip
        
        
  BuildPushImage:
    needs: [TrainModel]
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      - name: Download model.zip
        uses: actions/download-artifact@v2
        with:
          name: model.zip
          path: ReviewPredictor

      - name: Publish to Registry
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          dockerfile: ReviewPredictor/Dockerfile
          directory: ReviewPredictor
          image: aslotte/reviewpredictor
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  DeployImage: 
    needs: [TrainModel, BuildPushImage]
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
                
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.CONTAINER_URL }}
          image: aslotte/reviewpredictor:${{ github.sha }}
          registry-login-server: docker.io
          registry-username: ${{ secrets.DOCKER_USERNAME }}
          registry-password: ${{ secrets.DOCKER_PASSWORD }}
          name: mlnet
          location: 'east us'
          
